// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Address
    {
        public Address()
        {
            Order_ = new HashSet<Order_>();
            Product = new HashSet<Product>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string provinceOrCity { get; set; }
        [Required]
        [StringLength(5)]
        public string provinceOrCityCode { get; set; }
        [Required]
        [StringLength(50)]
        public string district { get; set; }
        [Required]
        [StringLength(5)]
        public string districtCode { get; set; }
        [Required]
        [StringLength(50)]
        public string communeOrWard { get; set; }
        [Required]
        [StringLength(50)]
        public string streetAndHouseNum { get; set; }

        [InverseProperty("address")]
        public virtual ICollection<Order_> Order_ { get; set; }
        [InverseProperty("address")]
        public virtual ICollection<Product> Product { get; set; }
    }
}