// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class CartDetail
    {
        [Key]
        public int id { get; set; }
        public int productNum { get; set; }
        public int cartId { get; set; }
        public int productId { get; set; }

        [ForeignKey(nameof(cartId))]
        [InverseProperty(nameof(Cart.CartDetail))]
        public virtual Cart cart { get; set; }
        [ForeignKey(nameof(productId))]
        [InverseProperty(nameof(Product.CartDetail))]
        public virtual Product product { get; set; }
    }
}