// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Cart
    {
        public Cart()
        {
            CartDetail = new HashSet<CartDetail>();
            User_ = new HashSet<User_>();
        }

        [Key]
        public int id { get; set; }

        [InverseProperty("cart")]
        public virtual ICollection<CartDetail> CartDetail { get; set; }
        [InverseProperty("cart")]
        public virtual ICollection<User_> User_ { get; set; }
    }
}