// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Category
    {
        public Category()
        {
            Inverseparent = new HashSet<Category>();
            Product = new HashSet<Product>();
            Template = new HashSet<Template>();
        }

        [Key]
        public int id { get; set; }
        public int? parentId { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        public int level { get; set; }
        public int? imageId { get; set; }

        [ForeignKey(nameof(imageId))]
        [InverseProperty(nameof(Image.Category))]
        public virtual Image image { get; set; }
        [ForeignKey(nameof(parentId))]
        [InverseProperty(nameof(Category.Inverseparent))]
        public virtual Category parent { get; set; }
        [InverseProperty(nameof(Category.parent))]
        public virtual ICollection<Category> Inverseparent { get; set; }
        [InverseProperty("category")]
        public virtual ICollection<Product> Product { get; set; }
        [InverseProperty("category")]
        public virtual ICollection<Template> Template { get; set; }
    }
}