// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class DeliveryMethod
    {
        public DeliveryMethod()
        {
            Delivery = new HashSet<Delivery>();
        }

        [Key]
        public int id { get; set; }
        public int deliveryPartnerId { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        [Column(TypeName = "money")]
        public decimal pricePerKm { get; set; }

        [ForeignKey(nameof(deliveryPartnerId))]
        [InverseProperty(nameof(DeliveryPartner.DeliveryMethod))]
        public virtual DeliveryPartner deliveryPartner { get; set; }
        [InverseProperty("deliveryMethod")]
        public virtual ICollection<Delivery> Delivery { get; set; }
    }
}