// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Delivery
    {
        public Delivery()
        {
            Order_ = new HashSet<Order_>();
        }

        [Key]
        public int id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? startedAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? finishedAt { get; set; }
        [Required]
        [StringLength(10)]
        public string state { get; set; }
        public int deliveryMethodId { get; set; }

        [ForeignKey(nameof(deliveryMethodId))]
        [InverseProperty(nameof(DeliveryMethod.Delivery))]
        public virtual DeliveryMethod deliveryMethod { get; set; }
        [InverseProperty("delivery")]
        public virtual ICollection<Order_> Order_ { get; set; }
    }
}