// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Feedback
    {
        public Feedback()
        {
            Inverseparent = new HashSet<Feedback>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(500)]
        public string content { get; set; }
        public double? starNum { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createdAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updatedAt { get; set; }
        public int parentId { get; set; }
        public int userId { get; set; }
        public int productId { get; set; }

        [ForeignKey(nameof(parentId))]
        [InverseProperty(nameof(Feedback.Inverseparent))]
        public virtual Feedback parent { get; set; }
        [ForeignKey(nameof(productId))]
        [InverseProperty(nameof(Product.Feedback))]
        public virtual Product product { get; set; }
        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(User_.Feedback))]
        public virtual User_ user { get; set; }
        [InverseProperty(nameof(Feedback.parent))]
        public virtual ICollection<Feedback> Inverseparent { get; set; }
    }
}