// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Image
    {
        public Image()
        {
            ProductImage = new HashSet<ProductImage>();
            ProductOptionImage = new HashSet<ProductOptionImage>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(100)]
        public string description { get; set; }
        [Required]
        [StringLength(100)]
        public string fileName { get; set; }

        [InverseProperty("image")]
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        [InverseProperty("image")]
        public virtual ICollection<ProductOptionImage> ProductOptionImage { get; set; }
    }
}