// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Invoice
    {
        [Key]
        public int id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createdAt { get; set; }
        [StringLength(200)]
        public string note { get; set; }
        public int orderId { get; set; }

        [ForeignKey(nameof(orderId))]
        [InverseProperty(nameof(Order_.Invoice))]
        public virtual Order_ order { get; set; }
    }
}