// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Order_
    {
        public Order_()
        {
            Invoice = new HashSet<Invoice>();
            OrderDetail = new HashSet<OrderDetail>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(200)]
        public string note { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createdAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updatedAt { get; set; }
        public int addressId { get; set; }
        public int userId { get; set; }
        public int deliveryId { get; set; }
        public int paymentMethodId { get; set; }

        [ForeignKey(nameof(addressId))]
        [InverseProperty(nameof(Address.Order_))]
        public virtual Address address { get; set; }
        [ForeignKey(nameof(deliveryId))]
        [InverseProperty(nameof(Delivery.Order_))]
        public virtual Delivery delivery { get; set; }
        [ForeignKey(nameof(paymentMethodId))]
        [InverseProperty(nameof(PaymentMethod.Order_))]
        public virtual PaymentMethod paymentMethod { get; set; }
        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(User_.Order_))]
        public virtual User_ user { get; set; }
        [InverseProperty("order")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [InverseProperty("order")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
    }
}