// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class OrderDetail
    {
        [Key]
        public int id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createdAt { get; set; }
        public double? discountPercent { get; set; }
        [Column(TypeName = "money")]
        public decimal price { get; set; }
        public int productNum { get; set; }
        public int orderId { get; set; }
        public int productOptionId { get; set; }

        [ForeignKey(nameof(orderId))]
        [InverseProperty(nameof(Order_.OrderDetail))]
        public virtual Order_ order { get; set; }
        [ForeignKey(nameof(productOptionId))]
        [InverseProperty(nameof(ProductOption.OrderDetail))]
        public virtual ProductOption productOption { get; set; }
    }
}