// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class PaymentMethod
    {
        public PaymentMethod()
        {
            Order_ = new HashSet<Order_>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }

        [InverseProperty("paymentMethod")]
        public virtual ICollection<Order_> Order_ { get; set; }
    }
}