// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Permission
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }
        public int resourceId { get; set; }
        [Required]
        public bool? canRead { get; set; }
        public bool canWrite { get; set; }

        [ForeignKey(nameof(resourceId))]
        [InverseProperty(nameof(Resource.Permission))]
        public virtual Resource resource { get; set; }
    }
}