// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class ProductOptionValue
    {
        [Key]
        public int id { get; set; }
        public int productOptionId { get; set; }
        public int propertyId { get; set; }
        [Required]
        [StringLength(500)]
        public string value { get; set; }

        [ForeignKey(nameof(productOptionId))]
        [InverseProperty(nameof(ProductOption.ProductOptionValue))]
        public virtual ProductOption productOption { get; set; }
        [ForeignKey(nameof(propertyId))]
        [InverseProperty(nameof(Property.ProductOptionValue))]
        public virtual Property property { get; set; }
    }
}