// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class ProductOptionImage
    {
        [Key]
        public int id { get; set; }
        public int productOptionId { get; set; }
        public int imageId { get; set; }

        [ForeignKey(nameof(imageId))]
        [InverseProperty(nameof(Image.ProductOptionImage))]
        public virtual Image image { get; set; }
        [ForeignKey(nameof(productOptionId))]
        [InverseProperty(nameof(ProductOption.ProductOptionImage))]
        public virtual ProductOption productOption { get; set; }
    }
}