// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Product
    {
        public Product()
        {
            CartDetail = new HashSet<CartDetail>();
            Feedback = new HashSet<Feedback>();
            ProductImage = new HashSet<ProductImage>();
            ProductOption = new HashSet<ProductOption>();
            ProductPropertyValue = new HashSet<ProductPropertyValue>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public double starNum { get; set; }
        [Required]
        [StringLength(500)]
        public string description { get; set; }
        public int sellingNum { get; set; }
        public int remainingNum { get; set; }
        public int categoryId { get; set; }
        public int shopId { get; set; }
        public int addressId { get; set; }

        [ForeignKey(nameof(addressId))]
        [InverseProperty(nameof(Address.Product))]
        public virtual Address address { get; set; }
        [ForeignKey(nameof(categoryId))]
        [InverseProperty(nameof(Category.Product))]
        public virtual Category category { get; set; }
        [ForeignKey(nameof(shopId))]
        [InverseProperty(nameof(Shop.Product))]
        public virtual Shop shop { get; set; }
        [InverseProperty("product")]
        public virtual ICollection<CartDetail> CartDetail { get; set; }
        [InverseProperty("product")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        [InverseProperty("product")]
        public virtual ICollection<ProductImage> ProductImage { get; set; }
        [InverseProperty("product")]
        public virtual ICollection<ProductOption> ProductOption { get; set; }
        [InverseProperty("product")]
        public virtual ICollection<ProductPropertyValue> ProductPropertyValue { get; set; }
    }
}