// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class ProductOption
    {
        public ProductOption()
        {
            OrderDetail = new HashSet<OrderDetail>();
            ProductOptionImage = new HashSet<ProductOptionImage>();
            ProductOptionValue = new HashSet<ProductOptionValue>();
        }

        [Key]
        public int id { get; set; }
        [Column(TypeName = "money")]
        public decimal price { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public int productId { get; set; }

        [ForeignKey(nameof(productId))]
        [InverseProperty(nameof(Product.ProductOption))]
        public virtual Product product { get; set; }
        [InverseProperty("productOption")]
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        [InverseProperty("productOption")]
        public virtual ICollection<ProductOptionImage> ProductOptionImage { get; set; }
        [InverseProperty("productOption")]
        public virtual ICollection<ProductOptionValue> ProductOptionValue { get; set; }
    }
}