// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class ProductImage
    {
        [Key]
        public int id { get; set; }
        public int productId { get; set; }
        public int imageId { get; set; }

        [ForeignKey(nameof(imageId))]
        [InverseProperty(nameof(Image.ProductImage))]
        public virtual Image image { get; set; }
        [ForeignKey(nameof(productId))]
        [InverseProperty(nameof(Product.ProductImage))]
        public virtual Product product { get; set; }
    }
}