// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Property
    {
        public Property()
        {
            ProductOptionValue = new HashSet<ProductOptionValue>();
            ProductPropertyValue = new HashSet<ProductPropertyValue>();
            PropertyTemplate = new HashSet<PropertyTemplate>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        [StringLength(50)]
        public string secondaryId { get; set; }

        [InverseProperty("property")]
        public virtual ICollection<ProductOptionValue> ProductOptionValue { get; set; }
        [InverseProperty("property")]
        public virtual ICollection<ProductPropertyValue> ProductPropertyValue { get; set; }
        [InverseProperty("property")]
        public virtual ICollection<PropertyTemplate> PropertyTemplate { get; set; }
    }
}