// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Shop
    {
        public Shop()
        {
            Product = new HashSet<Product>();
            User_ = new HashSet<User_>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        public string name { get; set; }

        [InverseProperty("shop")]
        public virtual ICollection<Product> Product { get; set; }
        [InverseProperty("shop")]
        public virtual ICollection<User_> User_ { get; set; }
    }
}