// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Template
    {
        public Template()
        {
            Category = new HashSet<Category>();
            PropertyTemplate = new HashSet<PropertyTemplate>();
        }

        [Key]
        public int id { get; set; }

        [InverseProperty("template")]
        public virtual ICollection<Category> Category { get; set; }
        [InverseProperty("template")]
        public virtual ICollection<PropertyTemplate> PropertyTemplate { get; set; }
    }
}