// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class Template
    {
        public Template()
        {
            PropertyTemplate = new HashSet<PropertyTemplate>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        public int categoryId { get; set; }

        [ForeignKey(nameof(categoryId))]
        [InverseProperty(nameof(Category.Template))]
        public virtual Category category { get; set; }
        [InverseProperty("template")]
        public virtual ICollection<PropertyTemplate> PropertyTemplate { get; set; }
    }
}