// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class User_
    {
        public User_()
        {
            Feedback = new HashSet<Feedback>();
            Order_ = new HashSet<Order_>();
            UserRole = new HashSet<UserRole>();
        }

        [Key]
        public int id { get; set; }
        [StringLength(50)]
        public string name { get; set; }
        [Required]
        [StringLength(15)]
        public string phone { get; set; }
        [StringLength(15)]
        public string email { get; set; }
        [Required]
        [StringLength(500)]
        public string password { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? createdAt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? updatedAt { get; set; }
        public int cartId { get; set; }
        public int? shopId { get; set; }

        [ForeignKey(nameof(cartId))]
        [InverseProperty(nameof(Cart.User_))]
        public virtual Cart cart { get; set; }
        [ForeignKey(nameof(shopId))]
        [InverseProperty(nameof(Shop.User_))]
        public virtual Shop shop { get; set; }
        [InverseProperty("user")]
        public virtual ICollection<Feedback> Feedback { get; set; }
        [InverseProperty("user")]
        public virtual ICollection<Order_> Order_ { get; set; }
        [InverseProperty("user")]
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}