// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PandaShoppingAPI.DataAccesses.EF
{
    public partial class UserRole
    {
        [Key]
        public int id { get; set; }
        public int userId { get; set; }
        public int roleId { get; set; }

        [ForeignKey(nameof(roleId))]
        [InverseProperty(nameof(Role.UserRole))]
        public virtual Role role { get; set; }
        [ForeignKey(nameof(userId))]
        [InverseProperty(nameof(User_.UserRole))]
        public virtual User_ user { get; set; }
    }
}